// src/firebase/config.ts

// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

import { FirebaseOptions } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyADf55E9yq21dm0-Qx-n6ee0NCTM76QeGQ",
  authDomain: "orelis-med.firebaseapp.com",
  projectId: "orelis-med",
  storageBucket: "orelis-med.appspot.com",
  messagingSenderId: "833510399388",
  appId: "1:833510399388:web:185321195272685f3afc59",
  measurementId: "G-L5KT6KKJHC",
};

export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing Firebase config: Make sure to setup your environment variables.');
  }
  return firebaseConfig;
}
